---
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 2.4.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    repoURL: https://github.com/prometheus/prometheus.git
    targetRevision: v2.24.0
 
